version: '3.8'
services:
  apache:
    build:
      context: .
      dockerfile: server/apache/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: .
      dockerfile: server/graphql/Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "4000:4000"
    depends_on:
      - mysql

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "5173:5173"

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: degree_planner
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: 