version: '3.8'
services:
  apache:
    build:
      context: .
      dockerfile: server/apache/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: server/graphql/Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:root@mysql:3306/degree_planner
    depends_on:
      - mysql
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    networks:
      - app-network
    restart: unless-stopped

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: degree_planner
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local 